dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0
compiler:
  evm_version: null
  solc:
    version: "0.8.0"
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
dotenv: .env
